version: '3.8'

services:

  mongodb:
    image: mongo:8.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123
    networks:
      - app-network
	  
  app:
    build: main-server/
    container_name: app
    image: kumys-app
    volumes:
      - ./common-include:/common-include    # Не оч красиво, ибо все в корне
      - ./main-server:/app
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: "mongodb://root:123@mongodb:27017"
    networks:
      - app-network
    stdin_open: true
    tty: true
    restart: unless-stopped

  proxy:
    build: proxy-server/
    container_name: proxy
    image: kumys-proxy
    volumes:
      - ./common-include:/kumys/common-include             
      - ./proxy-server:/kumys/proxy-server
      - ./scripts:/kumys/scripts
    ports:
      - "63380:63380" # client -> nginx
      - "63370:63370" # buffer <- main_server
    networks:
      - app-network
    stdin_open: true
    tty: true
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
